apiVersion: v2
name: application
description: Generic helm chart for all kind of applications

type: application

# Helm chart Version

version: 3.0.15


keywords:
  - java
  - node
  - dotnet
  - kubernetes
  - stakater
  - application

home: https://github.com/saritasa-nest/stakater-application
maintainers:
- name: rtest12
  email: maxim.omelchenko@saritasa.com

icon: https://github.com/stakater/ForecastleIcons/blob/master/stakater.png
